[package]
name = "brickworks-rs"
version = "0.0.1"
authors = ["Federico Menegoz"]
description = "Rust port of the Brickworks audio DSP library"
edition = "2024"
license = "GPL-3.0-only"

[build-dependencies]
bindgen = "0.71.1"

[dependencies]
